mobs:
  example.schem:
    - name: ExampleMob
      mythic_id: example_id
      amount: 3

database:
  host: localhost
  port: 3306
  name: minesystem
  user: root
  password: password

sell-prices:
  world:
    COAL_ORE: 1.0
    IRON_ORE: 2.0
