mobs:
  example.schem:
    - name: ExampleMob
      mythic_id: example_id
      amount: 3

sell-prices:
  world: # nazwa świata
    Hematite: 1000000
    BlackSpinel: 1750000
    BlackDiamond: 3000000
    Magnetite: 1250000
    Silver: 2250000
    Osmium: 3500000
    Azurite: 1500000
    Tanzanite: 2500000
    BlueSapphire: 3750000
    Carnelian: 1625000
    RedSpinel: 2875000
    PigeonBloodRuby: 4375000
    Pyrite: 1875000
    YellowTopaz: 3125000
    YellowSapphire: 4500000
    Malachite: 2250000
    Peridot: 3250000
    TropicheEmerald: 5000000
    Danburite: 2500000
    Goshenite: 4375000
    Cerussite: 7500000
