mobs:
  example.schem:
    - name: ExampleMob
      mythic_id: example_id
      amount: 3

database:
  host: localhost
  port: 3306
  name: minesystem
  user: root
  password: password

sell-prices:
  world:
    Hematite: 40.0
    BlackSpinel: 70.0
    BlackDiamond: 120.0
    Magnetite: 50.0
    Silver: 90.0
    Osmium: 140.0
    Azurite: 60.0
    Tanzanite: 100.0
    BlueSapphire: 150.0
    Carnelian: 65.0
    RedSpinel: 115.0
    PigeonBloodRuby: 175.0
    Pyrite: 75.0
    YellowTopaz: 125.0
    YellowSapphire: 180.0
    Malachite: 90.0
    Peridot: 130.0
    TropicheEmerald: 200.0
    Danburite: 100.0
    Goshenite: 175.0
    Cerussite: 300.0
