name: mineSystemPlugin
version: '1.0-SNAPSHOT'
main: org.maks.mineSystemPlugin.MineSystemPlugin
api-version: '1.20'
commands:
  loot:
    description: Manage loot configuration
    usage: /loot add <item> <chance>
    permission: minesystemplugin.loot
