name: mineSystemPlugin
version: '1.0-SNAPSHOT'
main: org.maks.mineSystemPlugin.MineSystemPlugin
api-version: '1.20'
commands:
  spawnsphere:
    description: Spawns a mining sphere for testing
    usage: /spawnsphere
