name: MineSystemPlugin
version: '1.0-SNAPSHOT'
main: org.maks.mineSystemPlugin.MineSystemPlugin
api-version: '1.20'
commands:
  crystalenchant:
    description: Enchants a pickaxe using crystals
    usage: /crystalenchant

  spawnsphere:
    description: Spawns a mining sphere for testing
    usage: /spawnsphere

