name: MineSystemPlugin
version: '1.0-SNAPSHOT'
main: org.maks.mineSystemPlugin.MineSystemPlugin
api-version: '1.20'
depend: [Vault]
commands:
  loot:
    description: Manage loot configuration
    usage: /loot add <item> <chance>
    permission: minesystemplugin.loot
  mine:
    description: Open the mine selection menu
    usage: /mine
  mine_repair:
    description: Repair the item in your main hand using Crystals.
    usage: /mine_repair
  mine_enchant:
    description: Enchants a pickaxe using crystals
    usage: /mine_enchant

  spawnsphere:
    description: Spawns a mining sphere for testing
    usage: /spawnsphere
  specialloot:
    description: Edit loot for special schematics
    usage: /specialloot <schematic>
